### ISSUE TITLE
Stylize not functional?

### ISSUE THREAD

**Issue by jstvnsn** [0xC0000054/gmic-8bf#1]
hi, This is a great package (as a Photoshop plug-in). Well done. However, I cannot get the style transfer filter to work - see the screenshot here. Any ideas on how to fix that?

![Screenshot 2020-12-02 09 46 09](https://user-images.githubusercontent.com/4118955/100904128-f0307600-3483-11eb-953c-6e08ac6feaaf.png)

It does work correctly in this mode:

![Screenshot 2020-12-02 09 55 26](https://user-images.githubusercontent.com/4118955/100904863-ae53ff80-3484-11eb-9d9b-cd8485b73475.png)

**Comment by jstvnsn** [comment]
I overlooked a very important option - Input layers - hidden under a roll-up bar at the bottom of the UI there ....

**Comment by 0xC0000054** [comment]
> Input layers - hidden under a roll-up bar at the bottom of the UI there ....

I was confused by that as well when testing the plug-in.
The input layer options used to always be visible in the UI, I do not know when that changed.
