### ISSUE TITLE
unable to read all of the requested image data from a layer

### ISSUE THREAD

**Issue by DiegoRRR** [0xC0000054/gmic-8bf#14]
Hello

Sorry to tell you that there is still a bug with layers size in 3.02.1. Gmic can't open and says : "unable to read all of the requested image data from a layer".

Steps to reproduce the bug :
- I opened a drawing of mine
- I imported a painting (to use as a style for the stylise filter)
- I put the painting layer below my drawing's layer, and scaled it up (because the stylise filter doesn't work well if there is empty space around the layer)
- can't open g'mic
[00.zip](https://github.com/0xC0000054/gmic-8bf/files/8233338/00.zip)

The reason for this bug seems to be that the painting layer is bigger than the other. I found out that if I cut it, it works. Data outside of the boundaries should just be ignored though.

Thanks

**Comment by 0xC0000054** [comment]
This has been fixed for the next version.
