### ISSUE TITLE
GMIC not installing on Affinity Photo V2

### ISSUE THREAD

**Issue by Gojigirl** [0xC0000054/gmic-8bf#19]
Hi, it's not appearing in the Plugins list.  Not that Nik Collection 7 is either and I've emailed DxO about that.
I've followed the instructions that Nick Hayes (think that is his name) wrote in 2021.
Thanks for any help resolving this.

**Comment by 0xC0000054** [comment]
That sound like a bug in Affinity Photo 2. You should take it up with that program's developers.

I don't know if they changed the plugin install process since I wrote those instructions.

**Comment by Gojigirl** [comment]
Thank you Nicholas for your reply. I'll do that.
