### ISSUE TITLE
Filters only affect a square area if picture is taller than wider

### ISSUE THREAD

**Issue by Erkhyan** [0xC0000054/gmic-8bf#3]
Plugin version 1.1.0 x64

Tested on **Windows 10 r1910 + Photoshop 21.1 x64** and **Windows 10 r1910 + XnViewMP 0.97.1 x64**.

Everything looks correct in the preview, but if the picture is taller than wider, then clicking either Apply or OK causes the filter to be applied only to a square the same height as the picture’s width. e.g., if the picture is 960×1280 pixels, then only the upper 960×960 pixels are processed.

This does not happen with pictures that are wider than taller.

**Comment by 0xC0000054** [comment]
Fixed in version 1.1.1.
