### ISSUE TITLE
Crashes with 16 bit images.

### ISSUE THREAD

**Issue by irvcobb** [0xC0000054/gmic-8bf#4]
1.1.0 crashes when invoked on 16 bit images and takes Photoshop down with it. CC on Win 10. Poster on DPR is having similar issues with CS6. 1.1.1 shows the same behavior on CC.

**Comment by 0xC0000054** [comment]
I am not able to reproduce that crash with CC 2020 on Win 10.
Do you have a sample image that causes it, or does the crash occur with any 16-bit image?

**Comment by irvcobb** [comment]
![_MG_4457](https://user-images.githubusercontent.com/35406346/101719086-3aa78900-3a68-11eb-9a3f-7434b6032890.jpg)
This image will crash, but only in certain circumstances:
1. Open in PS through Camera Raw.
2. Make a duplicate layer.
3. Run G'MIC on the duplicate.
4. Crash
Doesn't crash if opened with ACR or if G'MIC is run without duplicating the layer.
Some images seem to never crash. This one seems to always crash if the above steps are followed.

**Comment by 0xC0000054** [comment]
> Open in PS through Camera Raw.

The image was uploaded as a JPEG, if it was a RAW file you will need to zip it.

**Comment by irvcobb** [comment]
Thanks!

**Comment by irvcobb** [comment]
Just tested 1.1.2 and the above image still crashes. Jpg upload was not an error - if Preferences is set to have Camera Raw open jpgs, this crash occurs consistently when the above procedures are followed. Glad for the 1.1.2 fix, but I think there's still something borken in there...
