### ISSUE TITLE
Not working with Paintshop Pro

### ISSUE THREAD

**Issue by migf1** [0xC0000054/gmic-8bf#5]
Hi,

thank you very much for making a Ps compatible version of the G'MIC plugin!

Works great on Ps but the last version that plays well with Paintshop Pro is v1.0.2. All newer ones give a weird Memory Error as soon as you hit the OK button, to go back to PSP: https://prnt.sc/wdnnqp

Tested on PSP 2021, PSP 2020 and PSP X7.. all x64 (never tried x32).

**Comment by 0xC0000054** [comment]
Thanks for the report.

Based on that error message it looks like the plug-in is reporting the Ps API 'out of memory' error to PSP.
That error code is used in a few places when processing the G'MIC output, I will know more once I get PSP 2021 installed in a VM and start debugging the plugin.

**Comment by migf1** [comment]
That would be great! Thank you very much! Please let me know if you need me to provide any other info that may help you pin point the issue.

**Comment by 0xC0000054** [comment]
Fixed in version 1.2.1.
