### ISSUE TITLE
Tell the user where to put it

### ISSUE THREAD

**Issue by ganego** [0xC0000054/gmic-8bf#8]
I downloaded this plugin for PS and the readme is not even remotely helpful:  

> Place GmicPlugin.8bf and gmic folder in the folder that your host application searches for filter plug-ins.

How should a normal user know where that is? So instead of having every user of this google the answer, just write it in the readme, so work has to be done only once.

The answer for PS is: `C:\Program Files\Common Files\Adobe\Plug-Ins\CC\`.

**Comment by 0xC0000054** [comment]
> How should a normal user know where that is? So instead of having every user of this google the answer, just write it in the readme, so work has to be done only once.

I cannot put the host plugin folder in the readme because it would depend on what host application is being used and its installation location.
Photoshop, Affinity Photo, XnView and any other compatible hosts would each have their own default folders that are searched for plugins.

**Comment by ganego** [comment]
> Photoshop, Affinity Photo, XnView and any other compatible hosts would each have their own default folders   

Exactly. So it's like five extra lines of text to cover all the most-used programs.

**Comment by dtschump** [comment]
@ganego , you are then welcome to contribute adding those lines in the README with the information you already know. That would be helpful indeed.

**Comment by ganego** [comment]
Here is the pull request: https://github.com/0xC0000054/gmic-8bf/pull/9

**Comment by 0xC0000054** [comment]
> The answer for PS is: `C:\Program Files\Common Files\Adobe\Plug-Ins\CC\`.

On a 64-bit machine that path would only work for the 64-bit Adobe CC applications.
The 32-bit CC applications would have to use `C:\Program Files (x86)\Common Files\Adobe\Plug-Ins\CC\`.

The `CC` portion of the path is also version specific, the CS6 suite uses `CS6` etc.
Adobe uses  `Hard Drive\Program Files\Common Files\Adobe\Plug-Ins\[Photoshop version number]` on their [Plug-In installation help page](https://helpx.adobe.com/photoshop/kb/plug-ins-photoshop-troubleshooting.html#Locatepluginfolders).

**Comment by ganego** [comment]
Updated: https://github.com/0xC0000054/gmic-8bf/pull/9/commits/ee49ae507da60d648df582772163e059faa9f4f1

**Comment by 0xC0000054** [comment]
The [gmic-8bf project wiki](https://github.com/0xC0000054/gmic-8bf/wiki) now hosts installation instructions for several popular hosts.
Using the wiki allows for much more detailed instructions for each host than could be provided in the plug-in readme.
